### ISSUE TITLE
Unsupported Device ID: Broadlink RM4 Pro (520b)

### ISSUE THREAD

**Issue by CameronJRAllan** [mlfunston/node-red-contrib-broadlink#105]
Adding a new Broadlink RM4 Pro with device type, **520b**, which is currently not supported.

`[
  {
    "mac": "ec0baeedf53a",
    "ip": "192.168.3.40",
    "typeid": "520b",
    "type": "Broadlink: Unconfigured Device Type: Log an issue with the device details and typeid returned as this may be a new device type.",
    "name": "智能遥控\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0002\u0000E��E\u0002\u0000\u0000\u0000+�KB\r\u0000\u0000\u0000",
    "cloud": false,
    "msgdata": [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      123,
      0,
      47,
      9,
      23,
      6,
      4,
      2,
      0,
      0,
      0,
      0,
      192,
      168,
      3,
      24,
      39,
      193,
      0,
      0,
      21,
      214,
      0,
      0,
      0,
      0,
      7,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      255,
      83,
      112,
      32,
      11,
      82,
      40,
      3,
      168,
      192,
      236,
      11,
      174,
      237,
      245,
      58,
      230,
      153,
      186,
      232,
      131,
      189,
      233,
      129,
      165,
      230,
      142,
      167,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      2,
      0,
      69,
      154,
      154,
      69,
      2,
      0,
      0,
      0,
      43,
      234,
      143,
      75,
      66,
      13,
      0,
      0,
      0,
      0
    ]
  }
]`

**Comment by meccip** [comment]
hello. did you find any answer for your problem ?
i am in the same situation.

**Comment by CameronJRAllan** [comment]
No response as of yet, I think this project is currently "dead".

**Comment by github-guthub** [comment]
Same situation here.

**Comment by meccip** [comment]
nice. we are trying to revive this !!

**Comment by mustafaguven** [comment]
same here

**Comment by mlfunston** [comment]
Added in v2.1.5

**Comment by meccip** [comment]
updated broadlink node to version 2.1.6 but still not working with 520b. i am waiting for a reply from other users with same issue.

**Comment by mustafaguven** [comment]
I gave up using node red, I have created a script on home asistant and call it on nodered

**Comment by Langer75** [comment]
Yes, same here. Use the version 2.1.6 but it does not work with 520b

**Comment by hiredgun** [comment]
yeah, same story :(

**Comment by Langer75** [comment]
as mustafaguven did it, I also use HA as gateway and trigger it with my nodered dashboard. It would be interesting what is different in the HA implementation?

**Comment by xX-Nexus-Xx** [comment]
Has ther any progress?? .. my device is identified as 520b but not able to commnicate with the device

**Comment by bitlocus-art** [comment]
I had the same issue with 520b, and spent a few hrs investigating the issue, comparing packets generated with the broadlink_cli.

Here are the two main issues:
1) 520b requires the MAC address IN REVERSE, e.g. A0B1C2D3E4F5  needs to be entered as F5E4D3C2B1A0
2) the encrypted payload needs to be PADDED to the next 16 bytes.

interim fix, until a new version is released that addresses the issue:

here is a template code that you can use in NODERED, right before an RM node (you dont need to configure the RM node, just set it to Device: "none" and Action: from payload 

Add a function node ("on message" code) before the RM node, to populate the payload:

```
// BUGFIX for RM Pro 4, type 520b

var CODEHEX = "b1c03803ba...........1c1c0005dc";  // YOUR RF REMOTE BYTECODE AS HEX
// Convert HEX string to a Buffer
var data = Buffer.from(CODEHEX, 'hex');

// Calculate padding to make data length a multiple of 16
// (note that the plugin will add another header of 6 bytes)
const padding = (16 - ((data.length+6) % 16)) % 16;

// Add padding (all 0 bytes) to the data buffer
data = Buffer.concat([data, Buffer.alloc(padding)]);

var mac = "a0b1c2d3e4f5";  // your RMPRO4 mac  (not in reverse)
var host = "192.168.1.7";      // your RMPRO4 ip
msg.payload={
    "mac": Buffer.from(mac, 'hex').reverse().toString("hex"),  // need to reverse (bugfix)
    "host": host,  // Optional if configured in the RM node
    "devType" : "520b",
    "action":"send",
    "data":data
};

return msg;
```

**Comment by xX-Nexus-Xx** [comment]
thx I will give it a try

**Comment by xX-Nexus-Xx** [comment]
I did several tries, but it does not work :(

Is there a new version on horizon supporting the RM4 directly?

Or what is a better receiver/sender modul to be used?

**Comment by bitlocus-art** [comment]
in the screenshot you deleted, I noticed you were trying to use the broadlink_cli via the python command line. But the CLI is easier to use when actually being called as a CLI:
e.g. from Windows CMD line, go into the broadlink_cli directory 
cd python-broadlink\cli\
then run
python broadlink_cli --host 192.168.1.7 --mac E81656ABABC4 --type 0x520B --rflearn --frequency 433.85 --learnfile results.txt 
mkae sure you use your broadlink IP and MAC, this should write the results into the file results.txt when you press the button. if you leave out --learnfile then it will print on the screen isntead, or leave out --frequency 433.85 to get it to do the frequency check.

The result shoudl be a long string of hex bytes in the file, e.g. b1c03803ba9e06001d091d080a1b1d0a091c091c0b1b.....
This is your RF Code.

You can test the RF code also using the CLI: e.g.

python broadlink_cli --host 192.168.1.7 --mac E81656ABABC4 --type 0x520B --frequency 433.85 --type 0x520B --send b1c03803ba9e0600.....
(..... = use the full code here its usually a few hundreds bytes long)

Once that is confirmed working, you can start trying to use the same byte sequence in the NodeRed module

Where did you get stuck?

**Comment by bitlocus-art** [comment]
Once you have your working bytecode, you can use the code snippet above to populate the payload.msg in the function node ("on message" code) before the RM node, and then have the RM node read and evaluate that payload.msg

The RM Node does not even have to be configured ("Device" can remain at "Add ne rmdevice") as long as the Action is set to " - Set from msg.payload - " as we configure everythign in the payload (such as device IP and mac etc):

![Image](https://github.com/user-attachments/assets/9c69e211-fa9f-4a0e-a6b4-aba8f48a6ee9)

![Image](https://github.com/user-attachments/assets/8d567abe-0324-4609-b045-00e4e39549b3)
