### ISSUE TITLE
Update to SP04 / SP01

### ISSUE THREAD

**Issue by ChrisIDS6** [mlfunston/node-red-contrib-broadlink#107]
Hi,

Is ist possible to Update this, so that The SmartPlug4 can also be used? The typeid is a56c.
If possible also for SP01.... but thats not important. 

Thanks a lot
Christoph

**Comment by mlfunston** [comment]
Added a56c in v2.1.5

**Comment by ChrisIDS6** [comment]
Thanks a lot, doesn't work - but I think, it's because I cannot connect SP04 to the E-Control app (only to the newest "broadlink" app)
