### ISSUE TITLE
RM4Pro   typeid 5213 Broadlink: Unconfigured Device Type 

### ISSUE THREAD

**Issue by rthorn8** [mlfunston/node-red-contrib-broadlink#108]
{"_msgid":"a9c79a39e8f5695e","payload":[{"mac":"ec0baeee04f1","ip":"x.x.x.x","typeid":"5213","type":"Broadlink: Unconfigured Device Type: Log an issue with the device details and typeid returned as this may be a new device type.","name":"\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0002\u0001E��E\u0002\u0000\u0000\u0000\u0019�\n�B\r\u0000\u0000\u0000","cloud":false,"msgdata":[0,0,0,0,0,0,0,0,253,255,255,255,123,0,8,16,23,5,14,3,0,0,0,0,10,0,30,20,80,186,0,0,29,205,0,0,0,0,7,0,0,0,0,0,0,0,0,0,0,0,0,0,19,82,86,30,0,10,236,11,174,238,4,241,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,1,69,154,154,69,2,0,0,0,25,224,10,231,66,13,0,0,0,0]}],"topic":""}

**Comment by jamhos** [comment]
I have this same new device type:

![image](https://user-images.githubusercontent.com/59585318/236990444-c36513a3-ed72-403d-a1cf-f1dd356614cf.png)

**Comment by donchesworth** [comment]
Looks like it's mine too! Discover doesn't even work for me, but I pip installed broadlink, ran broadlink.discover(), and it showed devtype "21011", which in hex is 5213. Does someone want to fork this and add 5213? Looks like it's only needed in Constants.js and DiscoverNode.js

**Comment by mlfunston** [comment]
Added in v2.1.5

**Comment by donchesworth** [comment]
Discover works now! However, learn and send don't work - not even a message. I followed your resetting and stop at WIFI instructions twice. I even deleted the broadlink app from my iPhone and all data, and still nothing is working. Thoughts? Is there a way I could debug the process to see where the issue is?

Anyone able to get a 5213 to work?

**Comment by Langer75** [comment]
same with 520b

**Comment by UpgradedMR** [comment]
Anything further with this?  I have RM4 Pro with Type 520b as well. Discover works but learn/send do not.

![Image](https://github.com/user-attachments/assets/1f01af82-e6d4-4811-a5a2-92c524e96380)

Thanks

**Comment by Langer75** [comment]
I use the homeassistant implementation and configured a bridge to nodered. This works fine for me
