### ISSUE TITLE
Starting 

### ISSUE THREAD

**Issue by KeesKemper** [mlfunston/node-red-contrib-broadlink#12]
Starting node-RED gives the following issue:

7 Mar 10:32:21 - TypeError: Cannot read property 'code' of undefined
at /home/pi/.node-red/node_modules/node-red-contrib-broadlink-control/nodes/RMNode.js:92:143
nodered.service: Main process exited, code=exited, status=1/FAILURE
nodered.service: Unit entered failed state.
nodered.service: Failed with result 'exit-code'.

**Comment by mlfunston** [comment]
Do you have the jsonIrCode file populated with data in the correct format and the correct catalog folder path to the file in the RM node config?

**Comment by KeesKemper** [comment]
I have found out that there was an error in the Action set from the msg.payload. But that should not be a reason to stop the complete nodered service. In that way it's very complicated to make a correction.

**Comment by mlfunston** [comment]
Ok - Can you let me know what msg you sent in and I can see if the error handling can be improved to address it.

**Comment by KeesKemper** [comment]
The wrong msg I had sent in was:
- msg,payload,action = "send" (that's OK)
- msg,payload.remote = "2" (that's OK)
- msg.payload.button = "" (that's a not existing button)

**Comment by mlfunston** [comment]
Ok have added some error handling for this and will publish it in the next release.

**Comment by mlfunston** [comment]
Updated in v1.0.8
