### ISSUE TITLE
Broadlink as an IR reciever?

### ISSUE THREAD

**Issue by michaltaberski** [mlfunston/node-red-contrib-broadlink#15]
Hi, 

I wonder if it's possible to setup Broadlink as an IR receiver. What I would like to do is to use my universal traditional IR remote, and use it to control light. I can already control light through node-red. More or less like this:

```
REGULAR IR REMOTE -> BROADLINK -> NODE RED -> LIGHT
```

Technically Broadlink has IR reciever because it can learn from other remotes, but can it be used permanently through node-red?

**Comment by mlfunston** [comment]
It can’t as it is currently set up in the node but I can see if it’s possible to create a new continuous receiver node to continually spit out the IR codes.

You would then need to process them and filter out the other signals it receives though as it will be listening to any IR signals. 

I have a Logitech remote doing something similar but was going to look at using the broadlink instead. 

I’ll look into it. 

Mark Funston

**Comment by michaltaberski** [comment]
Thanks! Looking forward. I am pretty new to node-red but if I could support you anyhow please let me know.

**Comment by mlfunston** [comment]
I've done some testing on this. It seems that the Broadlink unit cannot be left open as a receiver all the time. When you ask it to receive data it will only keep the unit open to signals for 30 seconds and then time out and stop receiving. It would probably need a firmware change to stop this I think unless anyone has any other ideas.

I have set up a test node and can poll the unit continuously but as soon as it sees a signal it sends it and closes the connection. Then we need to poll it again and reopen to receive IR signals again. Not the best result and I'm not sure if it will cause issues with the unit if we keep doing this to it...

So it's probably not going to happen at this stage.
