### ISSUE TITLE
Question about passing data

### ISSUE THREAD

**Issue by phreaq** [mlfunston/node-red-contrib-broadlink#17]
I'm using the Broadlink nodes to turn off and on my ACs, and I found some code here and there to get me what I need:

> //Insert learning code here
> var data = [1,2,3,...];
> msg.payload={
>     //"mac":"MAC address of your broadlink rm",
>     //"host":"IP address of your broadlink rm",
>     "action":"send",
>     "data":data,
>     "repeat":2
> };
> 
> return msg;

My question is, what's the significance of the 'repeat' value? What affect does it have?

TIA

**Comment by mlfunston** [comment]
The repeat value was originally used to repeat sending the data stream to the device. However I think there were some issues with it and it's now no longer used and is stripped from the code. So you no longer need to include that .
