### ISSUE TITLE
RM.. - Code fix paramaeter

### ISSUE THREAD

**Issue by dr-boss** [mlfunston/node-red-contrib-broadlink#19]
I can'r find what doing this parameter. If I change from 1 to any other the send RF command not work. But what exactly happen I don't now. Please help me, thank.

**Comment by mlfunston** [comment]
The fix parameter appends another copy of the RF code string to the end of the current code string. It should only be used if it is required (I believe if the string is not divisible by 16). If you pull the code from the app it should be ok I think.

Note below from the readme also. The fix parameter does the appending of additional strings (eg setting 1,2 3, etc will add extra copies).

The TC2 device is not directly supported as it communicates via RF to the RM-Pro. However, if you have an RM Pro unit, you can pull the RF codes from the phone app after you have configured it and use those to control the switch. Note that you may need to send them multiple times to ensure it meets the requirements of being divisible by 16. Refer to this thread for similar process: https://github.com/ericmagnuson/rmcontrol/issues/4#issuecomment-269480450

**Comment by dr-boss** [comment]
Big thx for information. 
In my situation is interesting that after change 'fix' from 1 to 2 or other values the command stop working. The commands is on or off send from RMPro direct to 433Mhz wall plugs. With value 1 all work fine :-). The commands is learned by RMPro.
