### ISSUE TITLE
Broadlink RM 'learn' RF not working on recent RMPro+

### ISSUE THREAD

**Issue by Andrew49** [mlfunston/node-red-contrib-broadlink#20]
Unable to learn RF codes in Node-Red, using a recently bought RMPro+. I get "Please keep long press on the remote button until scan finishes." followed after some seconds by "Please tap the remote button." but even when I tap or hold the button nothing more happens, no message with the received codes or any other indication what is wrong. I can learn the codes for my two remotes ok with the Broadlink IHC app and successfully use the app to operate my blinds, so it appears to be a problem with the NR Learn routine.

**Comment by mlfunston** [comment]
It's possible that Broadlink may have changed the process on the newer units / firmware. 

Does anyone else have this working or not on older or newer units?

Unfortunately I don't have one to test with.

**Comment by alekob** [comment]
Same problem here, last message after ~ 30 seconds: "Broadlink Timeout Received - Closing Device Connection"
Using RedMatic 5.5.2, node-red-contrib-broadlink-control 1.0.8

**Comment by hpascual** [comment]
Same here. 
I used to use Homebridge and I got the RF Codes in the following format: "b2000302360a0c150c140c140c15160a170a160a170a0b150c140c14170a17090c15160a160b0c14160a0c150c14170a0c140c150b1517090c150c140c150b150c140c150c140c14170a170a0b150c1417090c150c141604a150360a0c140c150c140c15160a160a170a160a0c150c140c14170a160a0c15160a160a0c15160a0c140c1517090c150c140c14170a0c140c150c140c140d140c150c140c14170a160a0c150b15160a0c150c141604a051360a0c150c140c140c15160a160a170a160a0c150b150c14170a160a0c15160a160a0c15160a0c140c15160a0c150b150c14170a0c140c150c140c150c140c140c150c14170a160a0c140c15160a0c150c141604a05136090d140c150c140c14170a160a1709170a0c140c150c14170a160a0c14170a160a0c14170a0c140c15160a0c140c150c15160a0c140c140c150c140d140c140c150b15170a160a0c140c15160a0c140c151604a050370a0c140c140c150c14170a160a160a170a0c140c140c151709170a0c14170a160a0c14170a0c140c15160a0c140c150c14170a0c140c140c150c140c150b150c140c15160a170a0c140c15160a0c140c1417a251350a0c150c140c150c14160a170a160a17090c150c140c15160a160b0c14160a170a0c14170a0c140c14170a0c150b150c1417090c150c140c150c140c150c140c140c15160a17090c150c1417090c150c14170005dc0c150c140c"

How do I convert them to the format expected in node red?

Best regards.

**Comment by mlfunston** [comment]
@Andrew49 , @alekob - Have published a new version with better support for the new RM nodes. Please try this one.

@hpascual - Check out the "Learn and Send Data" example code in the examples. Your IR codes need to be in the following format. Looks like yours are in hex and you would need to convert the byte pairs into decimal perhaps?
```
var data = [38,0,140,0,77,21,18,22,38,21,17,22,17,22,38,21,18,21,18,22,37,22,17,22,18,21,18,22,17,0,3,99,77,21,18,22,38,21,17,22,18,21,38,21,18,22,17,22,38,21,18,21,18,22,17,22,17,0,3,99,77,21,18,22,37,22,17,22,18,21,38,21,18,22,17,22,37,22,18,21,18,22,17,22,18,0,3,100,76,22,18,21,38,21,18,22,17,22,37,22,18,21,18,22,37,22,17,22,18,21,18,22,17,0,3,101,76,22,18,21,39,20,18,22,17,22,37,22,18,21,18,22,37,22,17,22,18,21,18,22,17,0,13,5,0,0,0,0,0,0,0,0,0,0,0,0];
```
