### ISSUE TITLE
JsonIrCode file modification

### ISSUE THREAD

**Issue by sdalee** [mlfunston/node-red-contrib-broadlink#21]
Hello,

This is super control. Everything works fine,  but I have a little a problem.
I would like to switch off my Samsung TV, controlled by node-red. 
Unfortunately the Ir remote control of TV consist of one power button, so the node-red doesn't know that it switches off or on the tv.  
There are several Ir code pages on the internet (for example [samsung tv codes](http://www.remotecentral.com/cgi-bin/codes/samsung/tv_functions/) ), but I don't know how I can convert these hex codes to JsonIrCode file. 
Could you help me?
Thank you: John.

**Comment by mlfunston** [comment]
Easiest way is just to use the Learn and Send example and learn the power button code directly from the remote. Then store that and send it whenever you need.
