### ISSUE TITLE
Broadlink RM4 Mini Compatibility <Help Needed>

### ISSUE THREAD

**Issue by wenshyan** [mlfunston/node-red-contrib-broadlink#23]
Hello, 

Would this node be compatible to the new RM4 Mini? The link to the hardware as follows:

http://www.ibroadlink.com/products/ir-control

Thank you.

**Comment by mlfunston** [comment]
I have added in the newer device types, however there is a bugfix for the header that needs to be applied first in order to get them to work. I'll add this soon and release an update.

**Comment by mlfunston** [comment]
New version published that supports the new RM4 units. Try upgrading to that one.
