### ISSUE TITLE
hassio rmdevice node configuration

### ISSUE THREAD

**Issue by michalwu** [mlfunston/node-red-contrib-broadlink#24]
There is no info on how to configure catalog path. The only suggestion is windows path which is not helpful. 
https://flows.nodered.org/node/node-red-contrib-broadlink-control gives me this:
'Fill in the MAC address of the device, IP address and the full path to the SharedData folder in the Catalog field and click Add'

Does this mean 'SharedData' name is expected somewhere down the path?

mike

**Comment by mlfunston** [comment]
When you extract the SharedData folder from your phone, you need to put it somewhere that node red can access it. You need the full path to it in that field.
So on a raspberry pi, that might be /home/pi/SharedData if that is where you put the folder and files.

**Comment by michalwu** [comment]
Thank you for explanation. So I assume SharedData name is expected.

**Comment by mlfunston** [comment]
Yes, if you have not renamed it.
