### ISSUE TITLE
Broadlink RM4 Pro Compatibility

### ISSUE THREAD

**Issue by GeorgeLee888** [mlfunston/node-red-contrib-broadlink#28]
Would this node be compatible to the new  RM4 Pro.
I can’t control it with the version 2.0.0 .
The link to the hardware as follows:
[http://www.ibroadlink.com/products/ir+rf](http://www.ibroadlink.com/products/ir+rf)

Discover :
typeid: "6026"
type: "RM4 Pro"

Thank you !

**Comment by mlfunston** [comment]
The new v2.0 should work with that version. If it's not working right now then we may need to add that typeid to the newer header functions. I'll do a new release over the weekend and change that typeid to the new format.

**Comment by mlfunston** [comment]
Have added the 6026 device type to the RM4 types configuration in v2.0.1. So it should work once I deploy that one and you update. Will deploy today.

**Comment by mlfunston** [comment]
Updated in v2.0.1 and published
