### ISSUE TITLE
I have got problem to access this repository

### ISSUE THREAD

**Issue by Edu-ST** [mlfunston/node-red-contrib-broadlink#29]
Hi @mlfunston 

Could you help me?  
I was trying to access this your repository of this SmartApps, to get the set of node-red nodes to manage the Broadlink.
Thank you !!

**Comment by mlfunston** [comment]
Sorry, what is the SmartApps repository you are referring to?

**Comment by Edu-ST** [comment]
Hi,

This one:  mlfunston/node-red-contrib-broadlink-control

I would like to do the integration of Broadlink (RM4 mini), and I find this integration to use on Groovy there, is it right?

The process is add the repository on GitHub Repository Integration, and  to do de Update from Repository, ok?

Tks

**Comment by mlfunston** [comment]
Yes, I think that would be correct. I'm not familiar with Groovy, so I couldn't really provide any assistance on that side sorry.

**Comment by Edu-ST** [comment]
How can I do to  use your integration?  What is the proccess?  Could you explain?

**Comment by mlfunston** [comment]
It needs to be used in Node-RED.
