### ISSUE TITLE
Error Dashboard

### ISSUE THREAD

**Issue by odenisnobre** [mlfunston/node-red-contrib-broadlink#3]
After installation and configuration of the component it worked normally.
But I've noticed that the Dashboard has been bugged since:
![image](https://user-images.githubusercontent.com/8119694/48673373-d08db580-eb27-11e8-9aa2-cedf835dc0b1.png)

**Comment by mlfunston** [comment]
I don't have that issue. Is there any other item it could be? A reboot of the node perhaps?

**Comment by odenisnobre** [comment]
I already did this and it was not resolved.

What he decided was to change the door of the NR from 1880 to 2410.

With that he did not present any more problems. I do not know if other devices could interfere with the ports.

**Comment by mlfunston** [comment]
Ok, seems to be some clash somewhere with ports. The Broadlink messages are sent via UDP from a random port but it shouldn't interfere with the dashboard. I'll close this now it's sorted for you.
