### ISSUE TITLE
RM4 pro and RM4c mini

### ISSUE THREAD

**Issue by lemojack** [mlfunston/node-red-contrib-broadlink#30]
Hi,
I have problem with adding these devices to Node-Red. Discover shows me :

RM4 Pro 
Discover:
typeid: "6026"
type "RM4 Pro"

RM4C mini
Discover:
typeid: "62be"
type "RM4c"

I use example learn/send data for learning IR codes. In both cases when I try to learn IR codes I received debug message :
"Broadlink Timeout Received - Closing Device Connection"

RM4 Pro node config :
![rmpro1](https://user-images.githubusercontent.com/57143614/78546780-4d453080-77fe-11ea-8249-dd7eb95a2c53.png)
![rmpro2](https://user-images.githubusercontent.com/57143614/78546784-4f0ef400-77fe-11ea-99a5-e5b791d2c1ff.png)

My config : 
Node-RED v. 1.0.4
node-red-contrib-broadlink-control v. 2.0.0

**Comment by mlfunston** [comment]
Did you add the Catalog file (SharedData) from the mobile app?

**Comment by lemojack** [comment]
In e-control app the RM4 pro appears to me as unknown device and I can't use it. I can use both device RM4 pro and RM4C mini in Broadlink- Universal Remote app. 

This unknown device in e-control app generate some dir in path _/broadlink/newremote/SharedData/_ 
According to the guide I just shared the data from e-control through WLAN and copy the whole dir _SharedData_ 
I'm using Node-RED as add-on to homeassistant so I add path _/config/SharedData_ where I put dir from e-control, but the result is exactly the same.

**Comment by karmarcharger** [comment]
Facing the same issue here, using the iphone version of the app 


i checked in the e-control app there is additional files, but sadly as mentioned above it doesnt work for RM4 Pro. Below is the files in the econtrol app https://apps.apple.com/sg/app/broadlink-e-control/id793152994
![image](https://user-images.githubusercontent.com/10364143/78852998-66452000-7a50-11ea-8b5a-dea9b2f81ca5.png)
Inside ConCode folder of econtrol app
![image](https://user-images.githubusercontent.com/10364143/78853242-fbe0af80-7a50-11ea-8c69-9abe8b4b8fde.png)

Compared with the other app https://apps.apple.com/us/app/broadlink/id1450257910
![image](https://user-images.githubusercontent.com/10364143/78853120-b58b5080-7a50-11ea-9470-fceeb0699f0b.png)
Inside the ConCode file of other app
![image](https://user-images.githubusercontent.com/10364143/78853206-e8cddf80-7a50-11ea-8521-77cec583de71.png)

**Comment by mlfunston** [comment]
Ok - the newer versions don't work with the older app. There is a development task to use the DB from the newer IHC app, but I've not had time to work on that yet.

In the meantime, you could try the BroadlinkDB folder in this repository as your SharedData folder. The 4 files in it are the ones that are needed from it. You just need to update the details in the files.

**Comment by lemojack** [comment]
Should I update all parameter in the jsonDevice? Because when I change mac, type, password and publicKey to this one which I have from e-control app it's still not working.

**Comment by mlfunston** [comment]
I have added the 6026 device type to the RM4 configuration as it was missing. This will be updated in the next release v2.0.1.

**Comment by mlfunston** [comment]
IHC App support is covered in issue #9 so will address it on that.

**Comment by mlfunston** [comment]
6026 device type issue fixed in v2.0.1 and published
