### ISSUE TITLE
v2.0.0 new field in the device configuration

### ISSUE THREAD

**Issue by Maximus1** [mlfunston/node-red-contrib-broadlink#31]
v2.0.0 (latest)
Note - This version introduces a new field in the device configuration which will require a manual change to each device configuration.

what does this mean?
I have a RM3 mini. What do i have to insert?

**Comment by mlfunston** [comment]
If you have one of the older devices that was working before, you just need to insert the default value in the new field in the config.

**Comment by Maximus1** [comment]
what is the default value?
it is empty and everything works. only node red is telling me the node is missconfugured. would be nice to have it without that notice.

**Comment by mlfunston** [comment]
The default value was in there as 272a. You just need to type that in or use the type from the discover.

**Comment by mlfunston** [comment]
Will change the default value behaviour here to add the default value and set it as a non required field.
