### ISSUE TITLE
Broadlink Timeout Received

### ISSUE THREAD

**Issue by thermseekr** [mlfunston/node-red-contrib-broadlink#33]
Hi there,

I had posted the text below in issue #25 but as it is closed I'm not sure if it gets seen. So I'm opening a new issue with the same title.

Thanks,
Tales

======================

Hello all,

I was very happy to have found these nodes, so thanks a lot to the developer and to everyone else helping with the development.

I have three RM Mini 3 units, the older one is firmware v57 and the two newer are firmware v44057. They all get discovered as type 2737:

```
0: object
   mac: "c8f742174b74"
   ip: "192.168.200.131"
   typeid: "2737"
   type: "RM Mini"
1: object
   mac: "24dfa736c1cc"
   ip: "192.168.200.133"
   typeid: "2737"
   type: "RM Mini"
2: object
   mac: "24dfa73658b8"
   ip: "192.168.200.132"
   typeid: "2737"
   type: "RM Mini"
```
When I run the Learn and Send learned code flows from the examples I also get the `Broadlink Timeout Received - Closing Device Connection` message after a few seconds. Do we need to add new headers for this type too?

Thanks,
Tales

**Comment by realjax** [comment]
I have an RM3 Mini (firmware: v44057) connected to my local network. When I use the Discover node I get this:
{
  "mac": "24dfa77a4ff9",
  "ip": "192.168.0.101",
  "typeid": "5f36",
  "type": "RM Mini 3 newer",
}

I am running version 2.0 but started receiving  'Broadlink Timeout Received' errors after initially being able to learn and send.  Restarting the RM mini 3 does not help.

**Comment by baldfox** [comment]
I too just started to receive this error? Anyone have a fix or a work around? It's a shame, for 12months, the RM3 has been rock solid :(

**Comment by realjax** [comment]
Just to elaborate.. Even a reset of the mini does not fix this.

**Comment by baldfox** [comment]
For what it's worth, I managed to find a work around in node-red. At least the nodes are still working, even if the home-assistant component has fallen over for now. https://www.thesmarthomebook.com/2020/04/13/broadlink-firmware-update-takes-down-home-assistant-component-see-my-node-red-workaround/

**Comment by realjax** [comment]
Thanks. But it is the Node Red component I'm having the problem occur with.☹️ So  I'm afraid your workaround will start failing at some point as well.

**Comment by baldfox** [comment]
Ah ok. On my setup i've updated to the latest version of node-red-contrib-broadlink-control (2.0), for type, i just put 2737 and left catalogue blank (it's running as an add-on on hassio).

**Comment by realjax** [comment]
Type 2737?  Then you're not using an 'Rm mini 3 newer' ?

**Comment by Spanishu** [comment]
Is there a way to put older firmware? I think it is related to the type Id 5f36....

**Comment by realjax** [comment]
> ...i just put 2737...

I tried type 2737 but it made no difference. I also uninstalled and reinstalled the nodes in Node Red but also to no avail. 

Further info: According to the broadlink app the firmware of my RM Mini 3 is  **v44057**

**Comment by baldfox** [comment]
I just put in 2737 because it's the type that the node tells me when i use the "discover ID..." node. I don't know what firmware i'm on. I've not used the app since i got it added to the wifi. Quite frankly the broadlink app and the ihc app or whatever wasn't great. I don't want to open them again in case they bork my install! I've had bad experiences with tuya and their smart life app.

**Comment by realjax** [comment]
> in case they bork my install

You might have a point there. Everything was running fine here and all of a sudden I am only getting timeouts. Might very well be caused by a forced firmware update of the app.

**Comment by baldfox** [comment]
I've switched off auto update on the two apps (broadlink and eIHC) on my android device, and am even contemplating blocking the RM mini from reaching out to the internet.

**Comment by mlfunston** [comment]
My RM3 3 Mini with firmware version 44057 works fine with v2.0.0 of this node. I can learn and send commands.
I have the config node configured with: the MAC, IP Address, device type as 272a, and the catalog file location from the eControl app. It also works if I put in the device type as 2737 as reported from the discover node.
I also have some version 50 firmware devices and these are also fine.

If your discover node is reporting a different type ID such as 5f36, then that's probably another issue. That's the newer RM 3 mini which needs the correct type ID used as I understand it.

**Comment by mlfunston** [comment]
BTW - The `Broadlink Timeout Received - Closing Device Connection` message is actually normal. I'll update the message to log instead of warn.
This was added to stop the node from continually opening new connections and never closing them, so there is a timeout after 30 seconds to close the connection. We just had a message there to notify it. So this is fine.

**Comment by thermseekr** [comment]
Hello @mlfunston thanks for the replies. My RM3 Minis work well either with type 2737 as discovered by the Discover node or with type 272a as you use on yours. My only issue was with the timeout message, which I thought was an error. Now I know why they're there it's Ok.

I run Node-RED as an add-on to Home Assistant. Tha last update to the broadlink component on V0.108.6 solved the problem of RM3 Minis with firmware 44057 not working. So now I have options.

Will now try the configuration files.
