### ISSUE TITLE
compatibility with econtrol app rm4 pro

### ISSUE THREAD

**Issue by Jacopos94** [mlfunston/node-red-contrib-broadlink#35]
hi, i am a bit of a newby on nodered and on programming in general so i would like to ask for a bit of help since i got a broadlink rm4 pro ( this model https://www.ibroadlink.com/products/ir+rf) and it is not working with the econtrol app ( i managed to connect it to the app but is shown as some chinese characters and it says not recognized ) so i tried using the discover node but couldnt get it to discover the device even inserting by hand the MAC and the ip address of the rm4pro. i have 2 fields that remain empty namely the type and shared folder. What should i put in those field? and how would i then start gathering the inputs from the ir/rf dvices?

ps: i cant put any images right now since i am at work, will do as soon as i get home if needed

**Comment by mlfunston** [comment]
Ok - Discovery should work if the device has been configured in either the Broadlink E-Control or IHC app and you can see it in there. Once it is setup it should be discoverable on the network.

**Comment by mlfunston** [comment]
If you have set it up and still having issues, try this also.

Please try the troubleshooting here to see if it fixes the issue.
https://github.com/mlfunston/node-red-contrib-broadlink-control#new-broadlink-app-and-cloud-mode---troubleshooting
