### ISSUE TITLE
Broadlink timeout received still.

### ISSUE THREAD

**Issue by realjax** [mlfunston/node-red-contrib-broadlink#37]
Very well, new issue then. 

I have an RM Mini 3 (firmware: v44057) connected to my local network. When I use the Discover node I get this:
{
"mac": "24dfa77a4ff9",
"ip": "192.168.0.101",
"typeid": "5f36",
"type": "RM Mini 3 newer",
}

I am running version 2.0 but started receiving 'Broadlink Timeout Received' errors after initially being able to learn and send. Restarting the RM mini 3 does not help.

**Comment by realjax** [comment]
note: 
the type discovered was 5f36.
I tried both type 2737 and 2737 but to no avail.   The RM mini doesn't respond at all through the node but works fine when I use the app.

I tried resetting the RM to factory defaults many times. I reinstalled the Android app many times, I even tried on a different Node Red server running on a different OS.. but alas.  Doesn't work anymore with this node. :(

**Comment by thermseekr** [comment]
Hello @realjax sorry for closing my issue on you.

If I understood well, as mentioned [here](https://github.com/mlfunston/node-red-contrib-broadlink-control/issues/33#issuecomment-616095400) by @mlfunston the timeout message is probably unrelated to the problem your facing.

**Comment by realjax** [comment]
Yes, don't worry about it. My problem is indeed of a different kind. Just ends in the same error message 🙂

**Comment by realjax** [comment]
Ok, I have managed to 'reset'  my rm mini 3 using the broadlink-python API. By executing the setup() method from that api, I could use it again but now the broadlink app does no longer work for me. There is definitely something funky going on.

See here for more info: https://github.com/mjg59/python-broadlink/issues/307

**Comment by mlfunston** [comment]
Seems there is a known issue with the RM3 Mini Newer version (device type 5f36) connecting itself to the cloud which results in it not being able to authenticate locally any more.

Please try the troubleshooting here to see if it fixes the issue.
https://github.com/mlfunston/node-red-contrib-broadlink-control#new-broadlink-app-and-cloud-mode---troubleshooting

**Comment by mlfunston** [comment]
Consolidated to enhancement issue #42
