### ISSUE TITLE
Can not get it to work

### ISSUE THREAD

**Issue by dober2** [mlfunston/node-red-contrib-broadlink#39]
Hello,

i successfully discovered my device with the discovery node and put the data into the configuration of the RM node. Then i chose "Learn" as Action, but there is no reaction after an injection. The only thing that appears after some time in the node-red console log is "[RM:RM Mini 3 newer] Broadlink: Closing Device Connection". I also tried to send some dummy remote command data to see if the RM3 shows a reaction like a blinking light, but nothing.
Is there any way to get it to work?

Edit: Device type is: 5f36

**Comment by mlfunston** [comment]
Seems there is a known issue with the RM3 Mini Newer version (device type 5f36) connecting itself to the cloud which results in it not being able to authenticate locally any more. 

Please try the troubleshooting here to see if it fixes the issue.
https://github.com/mlfunston/node-red-contrib-broadlink-control#new-broadlink-app-and-cloud-mode---troubleshooting

**Comment by deadly667** [comment]
@dober2 Usually problem it is that you already set up device via Mobile app and choose some Remote control code setup. When you select some target device through mobile app, device enters into mode where he cannot receive nor learn commands via wifi anymore.  To get it working again, you need to delete any settings you made via Mobile app, reset RM Mini 3, clear cache and data from Mobile Broadlink application and then again set up RM mini 3 but after you enter wifi and password YOU NEED to stop there. Do not set up any further steps.  

Hope this helps.

**Comment by dober2** [comment]
Thank you for your help guys.
Since i set up many scenes and devices i rather stay with my current setup. What i do now to control the RM with node-red is triggering alexa routines which contain RM functions imported with the broadlink skill.
