### ISSUE TITLE
node-red-contrib-broadlink-control with HASSIO

### ISSUE THREAD

**Issue by BSD31** [mlfunston/node-red-contrib-broadlink#40]
Hello.
I am very interested in your work 'node-red-contrib-broadlink-control' but I can't get them to work properly.
My Node-Red is in a Docker container with Home Assistant.
I use the 'RM' node for my RM3-Mini type 272a but I cannot fill in the 'Catalog' field of 'Edit rmdevice node'.
So the learned codes do not register ...
My problem comes from the connection between Home assistant and Node-Red.
With other nodes, I use 'node-red-contrib-home-assistant-websocket' to communicate with Home Assistant.
Can I imagine that this is possible in this case?
Thank you

**Comment by mlfunston** [comment]
If you are mapping a data volume in Docker, then you could store the catalog files in that volume or folder location, eg map the config folder in your container to an external location, dump the SharedData folder in that location and then point to it as /config/SharedData

What data are you trying to send between the Broadlink nodes and Home Assistant?

Thanks.

**Comment by BSD31** [comment]
I would like my Samsung air conditioning to communicate with Home Assistant via Node-Red.
I created a folder '/ SharedData /' in the '/ config /' directory of Home Assistant and I indicated '/ config / SharedData' in the 'catalog' field of the node.
The white LED lights up well to learn a new code.
When the code is received, the white LED light is down but no file is saved in the indicated directory.
I can see the directory when I am in Windows via the address \\192.168.0.12\config\ShareData\ but it remains permanently empty ...
Thank you for your help.
Bruno from France

**Comment by BSD31** [comment]
Perhaps important information:
My Hassio is installed in a Virtual Machine Manager on Synology.

**Comment by mlfunston** [comment]
@BSD31 - Did you use the example code to "add code to db"?

Also, can you read the data from the catalog file in the RM node - IE do the remote and button show up when selecting the send function in the action drop down?

**Comment by BSD31** [comment]
Hi
Here is my configuration :

![image](https://user-images.githubusercontent.com/11723095/81056281-91455700-8eca-11ea-8dd7-92cfb2e9f653.png)
![image](https://user-images.githubusercontent.com/11723095/81056342-ac17cb80-8eca-11ea-91b2-92a061a460f5.png)
![image](https://user-images.githubusercontent.com/11723095/81056506-ef723a00-8eca-11ea-8873-5de39f313172.png)
![image](https://user-images.githubusercontent.com/11723095/81056523-fa2ccf00-8eca-11ea-9b36-39fb182c69c7.png)
![image](https://user-images.githubusercontent.com/11723095/81056628-21839c00-8ecb-11ea-885a-0f43256f5fb5.png)

Regards

**Comment by BSD31** [comment]
The Broadlink RM3
- Goes well in learning mode.
- Receive the signal
- But where does he save this code?

**Comment by mlfunston** [comment]
Have you followed the instructions in the readme to extract your econtrol app SharedData folder and put that in the \config\broadlink_data folder or copied in the example db from the node?

**Comment by BSD31** [comment]
![image](https://user-images.githubusercontent.com/11723095/81057684-319c7b00-8ecd-11ea-9ab2-04aa74cacb86.png)

for the sending part, the drop-down lists 'Remote' and 'Button' are empty

**Comment by BSD31** [comment]
I do not want to use the e-control application and indicate my wifi passwords on the Chinese site!
Can you use your node without registering on e-control?
I'm sorry but my English is very light and I use Google translation to write here ...
Maybe that's why I don't understand everything ...

**Comment by mlfunston** [comment]
If you don't want to extract the econtrol files, you at least need to have the JSON data files from the BroadlinkDB folder from this repository. Otherwise, where will it try to put the data in your folder when it's empty? No files in the folder = Not working. 

This is clearly mentioned here: https://github.com/mlfunston/node-red-contrib-broadlink-control#installing-and-setting-up

**Comment by mlfunston** [comment]
@BSD31 - Did you try with the sample broadlinkDB files and did that improve things?
