### ISSUE TITLE
ENHANCEMENT: Read IR data from compatible devices

### ISSUE THREAD

**Issue by PaoloTK** [mlfunston/node-red-contrib-broadlink#43]
From the Broadlink app once I add my Samsung AC unit I can see the room temperature and other similar information. Would it be possible to add a node to read this kind of information?

**Comment by thermseekr** [comment]
That made me curious. Can you share the model of your AC unit? Are you sure room temp in not coming from the Broadlink? Afaik RM Pros include a temperature sensor, maybe also humidity, not sure.

**Comment by PaoloTK** [comment]
> That made me curious. Can you share the model of your AC unit? Are you sure room temp in not coming from the Broadlink? Afaik RM Pros include a temperature sensor, maybe also humidity, not sure.

Thank you for the quick reply.
It's a Samsung AR09NXFPEWQN mini-split. I'm positive the temperature comes from the AC unit because I have an RM4 Mini without the additional USB sensor and I can see the temperature only in the AC remote page on the app. I can also see the temperature on the physical remote, so the unit must communicate it over IR.

**Comment by mlfunston** [comment]
@PaoloTK - If you are seeing a single temperature in the Broadlink App, this is the temperature setpoint, not the temperature in the room.
![Broadlink App Image](https://user-images.githubusercontent.com/27909227/80959180-da4ccb00-8e38-11ea-9e3e-65f7fb5ee8f6.jpg)

The Broadlink RM units can only send, or learn. They do not have a bi-directional communications capability unfortunately. I had tried this in the RM Receiver node, however it can only keep the connection open for 30 seconds. A firmware limit in the units.

**Comment by thermseekr** [comment]
Mark, sorry to mess the topic, but I think this side note can be
interesting.

About open connections: I have RM3 Minis with different firmware versions.
On the unit with FW v57 (which I suppose is an older unit) I notice a
considerable lag to start the first transmission. Further transmissions
start much faster. For example if I need to change channel on a cable
receiver, three digits, the first digit takes longer to start but second
and third are instantaneous. This kind of messes my flow to send the three
digits sequentially, and forced me to increase delays. Last night I was
building the same flows for an unit with FW v44057 and I noticed even the
first transmission start instantly, no matter how long the unit had sat
unused. Is it possible that hardware on the newer unit is that faster (it
is different, I opened it), or could it be it never sleeps?



Em seg., 4 de mai. de 2020 às 07:57, Mark Funston <notifications@github.com>
escreveu:

**Comment by mlfunston** [comment]
@thermseekr - Not sure what the differences are in the firmware but I have both the 57 and 44057 firmware on different units. I don't notice any differences between them in my setup, but I'm only sending commands to A/C units. It could be related to processing on the device and the new firmware fixes that.

I do notice that sending a code or request does take time sometimes, but this is more related to NodeJS and how loaded my system is. If I send 3 commands in a row, then the first will take time as it's on the end of the processor queue waiting for other requests in front of it, but the subsequent commands are quick as they are after each other on the queue.

**Comment by GeorgeLee888** [comment]
Sorry for leaving the topic

The RM Pro + ,RM mini series is about to be discontinued, and the successor is the RM4 series

RM4 has a power cord, which contains a temperature and humidity sensor(is optional).
![1588743826880](https://user-images.githubusercontent.com/28617729/81141828-5ca3cf00-8fa0-11ea-97e7-cbfe2a261717.jpg)
![1588744101784](https://user-images.githubusercontent.com/28617729/81141839-63cadd00-8fa0-11ea-8303-1d7630cae182.jpg)

**Comment by mlfunston** [comment]
> Sorry for leaving the topic
> 
> The RM Pro + ,RM mini series is about to be discontinued, and the successor is the RM4 series
> 
> RM4 has a power cord, which contains a temperature and humidity sensor(is optional).
> ![1588743826880](https://user-images.githubusercontent.com/28617729/81141828-5ca3cf00-8fa0-11ea-97e7-cbfe2a261717.jpg)
> ![1588744101784](https://user-images.githubusercontent.com/28617729/81141839-63cadd00-8fa0-11ea-8303-1d7630cae182.jpg)

@GeorgeLee888 - Have added to a separate issue to build out the temp & humidity monitoring.

**Comment by mlfunston** [comment]
@PaoloTK @thermseekr - Are we ok to close this issue based on the above items:
https://github.com/mlfunston/node-red-contrib-broadlink-control/issues/43#issuecomment-623396820
https://github.com/mlfunston/node-red-contrib-broadlink-control/issues/43#issuecomment-623444180

**Comment by PaoloTK** [comment]
> @PaoloTK - If you are seeing a single temperature in the Broadlink App, this is the temperature setpoint, not the temperature in the room.
> ![Broadlink App Image](https://user-images.githubusercontent.com/27909227/80959180-da4ccb00-8e38-11ea-9e3e-65f7fb5ee8f6.jpg)
> 
> The Broadlink RM units can only send, or learn. They do not have a bi-directional communications capability unfortunately. I had tried this in the RM Receiver node, however it can only keep the connection open for 30 seconds. A firmware limit in the units.

You're right, I don't know why I didn't think of that, my bad.


> @PaoloTK @thermseekr - Are we ok to close this issue based on the above items:
> [#43 (comment)](https://github.com/mlfunston/node-red-contrib-broadlink-control/issues/43#issuecomment-623396820)
> [#43 (comment)](https://github.com/mlfunston/node-red-contrib-broadlink-control/issues/43#issuecomment-623444180)

Yes!

**Comment by thermseekr** [comment]
Yes!
