### ISSUE TITLE
New type for RM4 Pro

### ISSUE THREAD

**Issue by civictyp3r** [mlfunston/node-red-contrib-broadlink#45]
I tried to use the discover node and the debug messaged showed up with:
typeid: "61a2"
type: "Broadlink: Unconfigured Device Type: Log an issue with the device details and typeid returned as this may be a new device type"

Learn/Send command doesn't do anything when i tried to use it.

**Comment by mlfunston** [comment]
Updated in v2.1.1 to include the 61a2 model.
