### ISSUE TITLE
Please add: Broadlink SC1 Smart Switch WiFi APP 2,4 

### ISSUE THREAD

**Issue by get-command** [mlfunston/node-red-contrib-broadlink#49]
first of all many thaks for these Nodes...

I have a RM Pro and a S1C alarm system. it works great and very well.

my question:
I have a lot of wifi SC1 relays, unfortunately there are no nodes. Is this planned? 

This device can i found over the discover node:
![grafik](https://user-images.githubusercontent.com/67456251/85927109-3f0a2c00-b8a4-11ea-8664-c732f7c4bd46.png)

how can i integrate that?

https://de.aliexpress.com/item/33030753102.html

**Comment by mlfunston** [comment]
The SC1 devices I believe you can register them as an SP2 device with the SP2 node. Have you tried that one?

If it's a newer one I may need to modify some code to make it work. Let me know.

**Comment by get-command** [comment]
> 
> 
> The SC1 devices I believe you can register them as an SP2 device with the SP2 node. Have you tried that one?
> 
> If it's a newer one I may need to modify some code to make it work. Let me know.

Hi,
you're right, i can control this with the sp2 node! Perfect, now function!

**Comment by mlfunston** [comment]
Ok great - I'll note this in the node and readme also on the next release.
