### ISSUE TITLE
New type for RM4 Mini

### ISSUE THREAD

**Issue by ryan-mcxx** [mlfunston/node-red-contrib-broadlink#53]
I tried to use the discover node and the debug messaged showed up with:
typeid: "648d"
type: "Broadlink: Unconfigured Device Type: Log an issue with the device details and typeid returned as this may be a new device type"

Learn/Send command doesn't do anything when i tried to use it.

**Comment by ronnybugle** [comment]
I've got the same issue when trying to use my RM4 Mini.  I tried the typeid of 5f36 and that allows me to learn, but it doesn't seem to send properly for some commands.  We can only hope there's a fix coming for the 648d type..

**Comment by mlfunston** [comment]
Added this device in v2.1.2
