### ISSUE TITLE
Nodered crashes on send command for RM

### ISSUE THREAD

**Issue by samuellazea** [mlfunston/node-red-contrib-broadlink#57]
![Capture4](https://user-images.githubusercontent.com/6168211/97111699-03b02a80-16e9-11eb-80be-d3529e281cc3.JPG)

I try to send a remote command and cause of this entire nodered crashes. Any chance you could catch this error also? Thanks in advance

**Comment by mlfunston** [comment]
Found the issue, there was a typo. should have been node.error not node.err.

Will deploy in new version

**Comment by samuellazea** [comment]
Thanks lots. Standing by then

**Comment by mlfunston** [comment]
V2.1.2 deployed with this fix in.

**Comment by samuellazea** [comment]
Thanks again
