### ISSUE TITLE
New Type for RM4 Pro - 649b

### ISSUE THREAD

**Issue by fduchatelet** [mlfunston/node-red-contrib-broadlink#59]
Hi,

I tried to use the discover node and the debug messaged showed up with:
typeid: "649b"
type: "Broadlink: Unconfigured Device Type: Log an issue with the device details and typeid returned as this may be a new device type"

Learn/Send command doesn't do anything when i tried to use it.

**Comment by mlfunston** [comment]
Have added it in and will publish it soon once I've re-tested the other new updates. Perhaps put in the type id as 62be in the meantime if you want to try it.

**Comment by quadhammer** [comment]
I have the same error with that device type.  Using 62be works to learn codes, but not to report the temperature.  And yes I have the temperature cable, and it shows up correctly in Home Assistant.

Edit: actually, although the little yellow light comes on to learn codes, I can't successfully get them learnt with RF anyway.

**Comment by rodolfodegrande** [comment]
any news? I have the same problem here, the yellow light comes on using the 62be, but it doesn't learn the code.

**Comment by KDYR** [comment]
Hi, I also got a RM4 Pro which is type 649b. Would be grateful to get an update with that type covered...

**Comment by mlfunston** [comment]
Added in v2.1.4
