### ISSUE TITLE
button list names only appears with user defined codes

### ISSUE THREAD

**Issue by Boco10** [mlfunston/node-red-contrib-broadlink#6]
Hello,

Node-red , RM node, device properly set, action send, device chosen, button list 9/10 is empty names only appears on the ones which was defined by me inside the app, remote device, more tab.

**Comment by mlfunston** [comment]
Which version of the broadlink app were you using to pull the the SharedData folder from and was it iOS or Android? Perhaps there was some change to the file format now?
Can you send a copy of your SharedData folder perhaps?

**Comment by jcf6288** [comment]
I was just using the econtrol app with a SP3 outlet, and the energy is different than what shows in node red vs the app.  No shared data required.
________________________________

**Comment by mlfunston** [comment]
@jcf6288 - This item is for issue #7 not issue #6

**Comment by jairo-futurasmus** [comment]
The application does not seem to assign button names to the device templates.
For example, this configuration corresponds to a Samsung remote control, it only saves in the name of a button that I have assigned manually.

android 8
version: 3.8.16

[jsonButton.txt](https://github.com/mlfunston/node-red-contrib-broadlink-control/files/2835486/jsonButton.txt)
[jsonIrCode.txt](https://github.com/mlfunston/node-red-contrib-broadlink-control/files/2835513/jsonIrCode.txt)

**Comment by mlfunston** [comment]
Yes, correct. The app only puts in names in the ones you manually add/learn. Unfortunately the only way I can see to assign names to those buttons in the file exported (jsonButton) would be to manually add the name into the name section of the file itself. Then it will use that name for the buttons. There is no other text to display for that button in the file.

`{"id":1,"subIRId":1,"name":" ***INSERT BUTTON NAME HERE *** ","index":0,"x":0,"y":0,"type":0,"order":0,"background":"icon_1.png","galleryDrawableName":"","gallerySkinId":0}`

**Comment by mlfunston** [comment]
@jairo-futurasmus & @Boco10 - I have added some example code to edit the broadlink files directly and add new learned commands directly. I hope this is of assistance to you. Also refer to the readme as there are perhaps some relevant comments in there about the files themselves having bad characters in them.
