### ISSUE TITLE
New type for RM4C mini

### ISSUE THREAD

**Issue by Mr-Groch** [mlfunston/node-red-contrib-broadlink#62]
Hi, I have new RM4C mini that isn't supported:

`{"mac":"a043b007f7f5","ip":"192.168.1.132","typeid":"6539","type":"Broadlink: Unconfigured Device Type: Log an issue with the device details and typeid returned as this may be a new device type.","name":"智能遥控\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0002","cloud":false,"msgdata":[0,0,0,0,0,0,0,0,0,0,0,0,120,0,6,20,20,2,1,11,0,0,0,0,192,168,1,211,218,170,0,0,17,212,0,0,0,0,7,0,0,0,0,0,0,0,0,0,174,245,60,106,57,101,132,1,168,192,160,67,176,7,247,245,230,153,186,232,131,189,233,129,165,230,142,167,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0]}`

**Comment by Mr-Groch** [comment]
It works fine (learning and sending commands), when I set type to 62be (type for older RM4c mini devices) in rmdevice config node

**Comment by mlfunston** [comment]
Added in v2.1.4.
