### ISSUE TITLE
New type - RM4 mini 653a

### ISSUE THREAD

**Issue by Rain-ZG** [mlfunston/node-red-contrib-broadlink#67]
When I use discover command I get
typeid: "653a"
type: "Broadlink: Unconfigured Device Type: Log an issue with the device details and typeid returned as this may be a new device type."
name: "智能遥控"
cloud: false

I tried using different type ID (62be and 5f36) but it is not working correctly. It does send some codes and some not.
Also it cannot enter learn mode.

Can you please add support for it?
If anything else is needed from my side let me know

**Comment by cinusik** [comment]
> When I use discover command I get
> typeid: "653a"
> type: "Broadlink: Unconfigured Device Type: Log an issue with the device details and typeid returned as this may be a new device type."
> name: "智能遥控�"
> cloud: false
> 
> I tried using different type ID (62be and 5f36) but it is not working correctly. It does send some codes and some not.
> Also it cannot enter learn mode.
> 
> Can you please add support for it?
> If anything else is needed from my side let me know

Exactly the same here, it cannot enter learn mode. Same typeid 653a

**Comment by xtrmtrk** [comment]
I too am having the same problem.  Happy to donate a RM4 mini device to you if that will help with development & debugging.

**Comment by marioskamperis** [comment]
Same for me.
Cannot use device to learn 0x653a - RM4 mini

**Comment by bergetun** [comment]
Same here for me.. I think its the newer firmware on the ones coming out from Aliexpress (V52078)

**Comment by blackylion** [comment]
Same issue. Can be found with discover and 1.2.1, but not working at all. Can't read code, can't send code.

**Comment by mlfunston** [comment]
Added in v2.1.4
