### ISSUE TITLE
Energy Reading Incorrect

### ISSUE THREAD

**Issue by jcf6288** [mlfunston/node-red-contrib-broadlink#7]
Energy is not reading correctly in watts.  45w shows around 68 when pulled through NodeRed.

**Comment by mlfunston** [comment]
What device were you using?
I assume that the 45w was showing in some other application? 
The only thing I can see here is perhaps there is some ascii translation that is converting the 45 from a hex value to a decimal 68/69 value somewhere along the line.

Is anyone else having this issue?

**Comment by mlfunston** [comment]
Test release ready in v1.0.8
