### ISSUE TITLE
New device Broadlink RM4 pro (typeid: 649b)

### ISSUE THREAD

**Issue by lehminet** [mlfunston/node-red-contrib-broadlink#71]
Hello,
the discover node determined my newly purchased Broadlink RM4 pro device with typeid 649b. It is running with firmware V52079.

It seems that learning IR codes isn‘t possible by using nodes RM or RMReceiver. The device doesn‘t switch to learn mode and the nodes receive a timeout after 30 seconds.

At the moment I can‘t test the IR sending functionality because I don‘t have IR codes for my devices. I will try to obtain IR codes by using a known RM3 mini device in the next days.

If you need any additional information, please don‘t hesitate to contact me. I‘d be glad to help you solve this issue.

Thanks in advance for your efforts!
Best regards, David

**Comment by lehminet** [comment]
Hello,
I have obtained IR codes by using a RM3 mini device. Unfortunately it is not possible to send these codes with the mentioned RM4 pro device. So I assume, the device doesn‘t react to the commands learn / send.

Best regards,
David

**Comment by mlfunston** [comment]
I think this should be fixed in v2.1.4 now.

**Comment by lehminet** [comment]
I have tested v2.1.4 with my RM4 pro device and it works like a charm. Thanks a lot! :)
