### ISSUE TITLE
time out

### ISSUE THREAD

**Issue by sergiocntr** [mlfunston/node-red-contrib-broadlink#8]
Notice that, during learn, you have only 3 sec for send the beam ,or you'll get a uncaught exception.

`4 Jan 19:16:47 - [warn] [RM:broadRM] Please tap the remote button.
4 Jan 19:16:50 - [red] Uncaught Exception:
4 Jan 19:16:50 - TypeError: Cannot read property 'checkData' of null at Timeout._onTimeout (/home/pi/.node-red/node_modules/node-red-contrib-broadlink-control/nodes/RMNode.js:76:75)
    at ontimeout (timers.js:436:11)
nodered.service: Main process exited, code=exited, status=1/FAILURE
nodered.service: Unit entered failed state.
nodered.service: Failed with result 'exit-code'.
nodered.service: Service hold-off time over, scheduling restart.
Stopped Node-RED graphical event wiring tool.
Started Node-RED graphical event wiring tool.
`

**Comment by mlfunston** [comment]
Ok, this is probably related to issue #4. Will need to rearrange some code to fix it.

**Comment by sergiocntr** [comment]
Ok thank you so much for your attention Mark. I'm trying to integrate my
home system with Google assistant and the best as  I know is to make a
scene in broadlink app then synchronize with google.When I call the scene,
Node red should get the it ir code from your node and send a mqtt
command,upon the code of course. The mqtt part is all done,do you think can
I manage this? Thanks so much for your attention again if you mind a trip
in Italy I'm close to Venice. Regards. Sergio.

Il giorno dom 6 gen 2019, 03:44 Mark Funston <notifications@github.com> ha
scritto:

**Comment by mlfunston** [comment]
@sergiocntr - I believe I have this timeout fixed now. It should allow 30 seconds for the IR code to be learned. 
You can certainly learn and store the codes and then play them back using the nodes here. It's much the same as what I'm doing at my home.
Mark

**Comment by sergiocntr** [comment]
thank you so much also for last images added.
