### ISSUE TITLE
RM4pro-Node Red Discovery not working

### ISSUE THREAD

**Issue by FreekBos** [mlfunston/node-red-contrib-broadlink#85]
Hi, the concept is brilliant.... yet I've tried it all (I think) to get the device type of my (aliexpress) RM4pro:
- CentOS and NodeRed upgraded
- RM4pro is in 192.168.191.22
- NR is in 192.168.61.70 (pring from NR->RM4pro is stable 3-5msec)
- FW rule NR->RM4pro is ok, no antivirus, ips etc
- FW rule RM4pro->NR is ok, no antivirus, ips etc
- multicast rule NR->RM4pro is ok, data seems to flow according to byte-count
- multicast rule RM4pro->NR is ok, data seems to flow according to byte-count
- discovery node seems to run for 3 seconds and then reports "No Devices Found"... could be v1.0.5 issue#10 reintroduction?
Anyone and idea?
Thanks a mil!

**Comment by mlfunston** [comment]
Hi - It looks like you have NodeRed and the RM4 in different subnets?

Discovery and Setup both use a broadcast to 255.255.255.255, so unless it's in the same subnet the broadcast UDP packets are not sent through to the other subnet. Maybe the problem? 

Can you put them in the same subnet and try?

**Comment by FreekBos** [comment]
Hi @mlfunston Mark,
Yes, that's a very correct statement: I have a Fortigate Firewall, 3 WiFi networks with their own ssid and vlan.
And a VERY good hint.....!
The NodeRed is in a different subnet hence the multicast rules between the WiFi and the NodeRed network.
It would be a great feature to have a "discovery" more specific i.e. when the IP-address is know so the model/id can be discovered.
I'll create an ssid on the same vlan as the NR to find out the model/id and try to move from there.
Should you or anyone else have another way to retrieve the model/id, please let me know.
Kindest regards

**Comment by milkplus27** [comment]
@FreekBos did you ever get this working? I'm having a similar issue of NR not being able to discover my RM3 Mini, but both ARE on the same subnet. I tried setting up some firewall rules between the two IP addresses to allow traffic, too, but no dice. I am a bit stumped...

**Comment by FreekBos** [comment]
Nope, never got it to work... it's a poor situation but it is the way it is.
If I ever have the time, I'm going to try sniffing the subnet to see what happens.
IF systems are on the same subnet (wired and wifi) broadcast traffic SHOULD be allowed.... a firewall ONLY picks up traffic addressed to the gateway. Having said that... I'm thinking weather or not the BL even sends multicast traffic or even understands the principles of gateway addresses....
If anyone has an idea OR an alternative, I would be VERY happy

**Comment by mlfunston** [comment]
You would need to use a UDP broadcast relay on your router/firewall.
