### ISSUE TITLE
Unlock Broadlink Devices if locked to the Cloud

### ISSUE THREAD

**Issue by karmarcharger** [mlfunston/node-red-contrib-broadlink#91]
Existing Locked RM4 pros can be unlocked without resetting, just found out, you can have the best of both worlds, the cloud services and node-red. You can do this by unchecking the lock device property in the device property from within the app.

Step One:
Tap your RM 4 Pro
![image](https://user-images.githubusercontent.com/10364143/170830368-95743d9e-5c40-413e-9175-ae07e937b182.png)
 
Step Two:
 Tap the top right hand corner of the screen the triple dots button and tap the property button
![image](https://user-images.githubusercontent.com/10364143/170830402-9b62472f-b547-4988-baef-debb955afab9.png)

Step Three:
Uncheck the lock device option.
![image](https://user-images.githubusercontent.com/10364143/170830437-e9bd5ead-0cfd-4d6e-a14e-3283aa35929a.png)

Step Four:
Profit
![image](https://user-images.githubusercontent.com/10364143/170830513-8ca87eb5-3619-4149-b3ab-cc3a8b3a7d9f.png)

**Comment by mlfunston** [comment]
Added this to the readme in the 2.1.5 release

**Comment by doit4fun** [comment]
mine is not working... even though I have unchecked the unlock option... still node-red is not able to communicate with it. I'm seeing it on the router and I can see the IP and MAC... so the wifi connection works, doesn't work on local. Any other method to test it?
I'm using 
Firmware: v62093
sdk: 2.16.35
