### ISSUE TITLE
Where is the list of device types?

### ISSUE THREAD

**Issue by Jibun-no-Kage** [mlfunston/node-red-contrib-broadlink#93]
Where is the list of device types?  Node defaults to type 272a?  But no clue what device that is?  Phone App does not list a node type?  So how do we find out what type of device 'type' value we have?

**Comment by Jibun-no-Kage** [comment]
For those that might like the information... type 648a is RM 4 Mini.

**Comment by mlfunston** [comment]
Added in v2.1.5
