### ISSUE TITLE
Hey the link to how to disconnect device from cloud has no information, something moved or changed?

### ISSUE THREAD

**Issue by Jibun-no-Kage** [mlfunston/node-red-contrib-broadlink#97]
Hey the link to how to disconnect device from cloud has no information, something moved or changed?
The following directions DO NOT EXPLAIN ANYTHING.  THE LINK REFERENCED HAS NO INFORMATION.

To reverse this, you will need to reset the device.

Suggested process is as follows:

    Remove any existing configured devices or control in the Broadlink app.
    Reset device by long press (~6 seconds) the reset button with a pin or paperclip until the LED rapidly flashes.
    Use the BroadLink app to connect to WiFi (keep your phone close to RM). AND STOP!!
    Do nothing more, dont't add anything more in the app, quit the app and now use the node.

Thanks to https://github.com/QuadrifoglioVerde for the info here.

USE WHAT NODE? HOW?  Are you talking about the WIFI SETUP node??????

**Comment by mlfunston** [comment]
Added in v2.1.5 readme
